<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18966" started-at="2019-11-05T08:58:29Z" finished-at="2019-11-05T08:58:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18966" started-at="2019-11-05T08:58:29Z" finished-at="2019-11-05T08:58:48Z">
      <class name="tests.LoginTests">
        <test-method status="PASS" signature="classLevelSetup()[pri:0, instance:tests.LoginTests@46c670a6]" name="classLevelSetup" is-config="true" duration-ms="3546" started-at="2019-11-05T08:58:29Z" finished-at="2019-11-05T08:58:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classLevelSetup -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.LoginTests@46c670a6]" name="methodLevelSetup" is-config="true" duration-ms="79" started-at="2019-11-05T08:58:33Z" finished-at="2019-11-05T08:58:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="PASS" signature="invalidLoginTest_InvalidUserNameInvalidPassword()[pri:0, instance:tests.LoginTests@46c670a6]" name="invalidLoginTest_InvalidUserNameInvalidPassword" duration-ms="10275" started-at="2019-11-05T08:58:33Z" description="Invalid Login Scenario with wrong username and password." finished-at="2019-11-05T08:58:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest_InvalidUserNameInvalidPassword -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.LoginTests@46c670a6]" name="methodLevelSetup" is-config="true" duration-ms="1" started-at="2019-11-05T08:58:43Z" finished-at="2019-11-05T08:58:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="FAIL" signature="invalidLoginTest_EmptyUserEmptyPassword()[pri:1, instance:tests.LoginTests@46c670a6]" name="invalidLoginTest_EmptyUserEmptyPassword" duration-ms="3388" started-at="2019-11-05T08:58:43Z" description="Invalid Login Scenario with empty username and password." finished-at="2019-11-05T08:58:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pages.LoginPage.verifyLoginPassword(LoginPage.java:43)
at tests.LoginTests.invalidLoginTest_EmptyUserEmptyPassword(LoginTests.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:tests.LoginTests@46c670a6]" name="teardown" is-config="true" duration-ms="638" started-at="2019-11-05T08:58:47Z" finished-at="2019-11-05T08:58:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.LoginTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
